[build]
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Payment"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
