[build]
  # Command to deploy your frontend website (e.g., "npm run build")
  # command = "npm run build"
  
  # Directory where your functions are located
  functions = "netlify/functions"
  
  # Your frontend's build output directory (e.g., "build" or "dist")
  # publish = "build"